### ISSUE TITLE
Dataset Download Link

### ISSUE THREAD

**Issue by anindyasarkarIITH** [MadryLab/backgrounds_challenge#1]
Thank You for creating such important challenge. Can you Please share the dataset download link?

**Comment by andrewilyas** [comment]
Hi! The datasets should already be downloadable from the "releases" tab on the main page, I.e., https://github.com/MadryLab/backgrounds_challenge/releases

**Comment by anindyasarkarIITH** [comment]
Thank You very much. Are you planning to open source the Imagnet-9 training dataset soon? Though in the paper, techniques behind generating all different variants of ImageNet-9 samples are already mentioned.

**Comment by kaixiao** [comment]
Hi! We have just updated the README to include links to training data. Please let us know if you run into any further issues with that.

**Comment by anindyasarkarIITH** [comment]
Hi,
     Thank you very much.
