### ISSUE TITLE
Making sense of the output from `challenge_eval.py`

### ISSUE THREAD

**Issue by sayakpaul** [MadryLab/backgrounds_challenge#4]
Hi. 

If I have the following summary from `challenge_eval.py` what score should I report? 

```
Summary: 3897/4050 (96.22%) are vulnerable foregrounds.
```

**Comment by kaixiao** [comment]
Hi,

The challenge accuracy is 100 - (% of vulnerable foregrounds), so in this case your challenge accuracy would be 3.78%.

**Comment by sayakpaul** [comment]
Okay understood. Could you expand a little bit more on the following?

> The challenge accuracy is 100 - (% of vulnerable foregrounds),

In the ideal case, none among the 4050 examples is vulnerable?

**Comment by kaixiao** [comment]
Exactly. If none of the foregrounds are vulnerable, then your challenge accuracy is 100%.

**Comment by sayakpaul** [comment]
Thank you. I just say it's an amazing investigation. Thanks for open-sourcing all the necessary materials.
